//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.16 at 08:27:24 PM PDT 
//


package org.alpa.wjamec.pairings.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Base.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="Base"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Edmonton"/&gt;
 *     &lt;enumeration value="Vancouver"/&gt;
 *     &lt;enumeration value="Winnipeg"/&gt;
 *     &lt;enumeration value="Calgary"/&gt;
 *     &lt;enumeration value="Toronto"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Base")
@XmlEnum
public enum Base {

    @XmlEnumValue("Edmonton")
    EDMONTON("Edmonton"),
    @XmlEnumValue("Vancouver")
    VANCOUVER("Vancouver"),
    @XmlEnumValue("Winnipeg")
    WINNIPEG("Winnipeg"),
    @XmlEnumValue("Calgary")
    CALGARY("Calgary"),
    @XmlEnumValue("Toronto")
    TORONTO("Toronto");
    private final String value;

    Base(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Base fromValue(String v) {
        for (Base c: Base.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
