//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.18 at 09:29:19 PM PDT 
//


package org.alpa.wjamec.pairings.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditAnnotation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="CreditAnnotation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MinimumValue"/&gt;
 *     &lt;enumeration value="LegValue"/&gt;
 *     &lt;enumeration value="DutyValue"/&gt;
 *     &lt;enumeration value="TripValue"/&gt;
 *     &lt;enumeration value="RatioValue"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CreditAnnotation")
@XmlEnum
public enum CreditAnnotation {

    @XmlEnumValue("MinimumValue")
    MINIMUM_VALUE("MinimumValue"),
    @XmlEnumValue("LegValue")
    LEG_VALUE("LegValue"),
    @XmlEnumValue("DutyValue")
    DUTY_VALUE("DutyValue"),
    @XmlEnumValue("TripValue")
    TRIP_VALUE("TripValue"),
    @XmlEnumValue("RatioValue")
    RATIO_VALUE("RatioValue");
    private final String value;

    CreditAnnotation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CreditAnnotation fromValue(String v) {
        for (CreditAnnotation c: CreditAnnotation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
