//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.16 at 07:52:36 PM PDT 
//


package org.alpa.wjamec.pairings.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DutyAnnotation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="DutyAnnotation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MorningDuty"/&gt;
 *     &lt;enumeration value="RedEyeDuty"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DutyAnnotation")
@XmlEnum
public enum DutyAnnotation {

    @XmlEnumValue("MorningDuty")
    MORNING_DUTY("MorningDuty"),
    @XmlEnumValue("RedEyeDuty")
    RED_EYE_DUTY("RedEyeDuty");
    private final String value;

    DutyAnnotation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DutyAnnotation fromValue(String v) {
        for (DutyAnnotation c: DutyAnnotation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
