//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.16 at 08:27:24 PM PDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.alpa.wjamec.pairings.jaxb;
