//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.16 at 08:27:24 PM PDT 
//


package org.alpa.wjamec.pairings.jaxb;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pairing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pairing"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}PreliminaryPairing"&gt;
 *       &lt;attribute name="trip" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="pairing" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pairing")
public class Pairing
    extends PreliminaryPairing
{

    @XmlAttribute(name = "trip", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger trip;
    @XmlAttribute(name = "pairing", required = true)
    protected String pairing;

    /**
     * Gets the value of the trip property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrip() {
        return trip;
    }

    /**
     * Sets the value of the trip property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrip(BigInteger value) {
        this.trip = value;
    }

    /**
     * Gets the value of the pairing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPairing() {
        return pairing;
    }

    /**
     * Sets the value of the pairing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPairing(String value) {
        this.pairing = value;
    }

}
