//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.13 at 03:32:22 PM PDT 
//


package org.alpa.wjamec.pairings.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PairingAnnotation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PairingAnnotation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="OptimizedTrip"/&gt;
 *     &lt;enumeration value="OptimizedLock"/&gt;
 *     &lt;enumeration value="ManualTrip"/&gt;
 *     &lt;enumeration value="ManualLock"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PairingAnnotation")
@XmlEnum
public enum PairingAnnotation {

    @XmlEnumValue("OptimizedTrip")
    OPTIMIZED_TRIP("OptimizedTrip"),
    @XmlEnumValue("OptimizedLock")
    OPTIMIZED_LOCK("OptimizedLock"),
    @XmlEnumValue("ManualTrip")
    MANUAL_TRIP("ManualTrip"),
    @XmlEnumValue("ManualLock")
    MANUAL_LOCK("ManualLock");
    private final String value;

    PairingAnnotation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PairingAnnotation fromValue(String v) {
        for (PairingAnnotation c: PairingAnnotation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
