//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.16 at 07:52:36 PM PDT 
//


package org.alpa.wjamec.pairings.jaxb;

import java.math.BigInteger;
import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreliminaryPairing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreliminaryPairing"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="crew" type="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}Crew"/&gt;
 *         &lt;element name="initialDutyDays" type="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}InitialDutyDays"/&gt;
 *         &lt;element name="dutyDays" type="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}DutyDays"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="base" use="required" type="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}Base" /&gt;
 *       &lt;attribute name="pairingAnnotation" use="required" type="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}PairingAnnotation" /&gt;
 *       &lt;attribute name="timeAwayFromBase" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="credit" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *       &lt;attribute name="creditAnnotation" type="{https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd}CreditAnnotation" /&gt;
 *       &lt;attribute name="perDiem" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreliminaryPairing", propOrder = {
    "crew",
    "initialDutyDays",
    "dutyDays"
})
@XmlSeeAlso({
    Pairing.class
})
public class PreliminaryPairing {

    @XmlElement(required = true)
    protected Crew crew;
    @XmlElement(required = true)
    protected InitialDutyDays initialDutyDays;
    @XmlElement(required = true)
    protected DutyDays dutyDays;
    @XmlAttribute(name = "base", required = true)
    protected Base base;
    @XmlAttribute(name = "pairingAnnotation", required = true)
    protected PairingAnnotation pairingAnnotation;
    @XmlAttribute(name = "timeAwayFromBase", required = true)
    protected Duration timeAwayFromBase;
    @XmlAttribute(name = "credit", required = true)
    protected Duration credit;
    @XmlAttribute(name = "creditAnnotation")
    protected CreditAnnotation creditAnnotation;
    @XmlAttribute(name = "perDiem", required = true)
    protected float perDiem;
    @XmlAttribute(name = "length", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger length;

    /**
     * Gets the value of the crew property.
     * 
     * @return
     *     possible object is
     *     {@link Crew }
     *     
     */
    public Crew getCrew() {
        return crew;
    }

    /**
     * Sets the value of the crew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Crew }
     *     
     */
    public void setCrew(Crew value) {
        this.crew = value;
    }

    /**
     * Gets the value of the initialDutyDays property.
     * 
     * @return
     *     possible object is
     *     {@link InitialDutyDays }
     *     
     */
    public InitialDutyDays getInitialDutyDays() {
        return initialDutyDays;
    }

    /**
     * Sets the value of the initialDutyDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialDutyDays }
     *     
     */
    public void setInitialDutyDays(InitialDutyDays value) {
        this.initialDutyDays = value;
    }

    /**
     * Gets the value of the dutyDays property.
     * 
     * @return
     *     possible object is
     *     {@link DutyDays }
     *     
     */
    public DutyDays getDutyDays() {
        return dutyDays;
    }

    /**
     * Sets the value of the dutyDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link DutyDays }
     *     
     */
    public void setDutyDays(DutyDays value) {
        this.dutyDays = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link Base }
     *     
     */
    public Base getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base }
     *     
     */
    public void setBase(Base value) {
        this.base = value;
    }

    /**
     * Gets the value of the pairingAnnotation property.
     * 
     * @return
     *     possible object is
     *     {@link PairingAnnotation }
     *     
     */
    public PairingAnnotation getPairingAnnotation() {
        return pairingAnnotation;
    }

    /**
     * Sets the value of the pairingAnnotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PairingAnnotation }
     *     
     */
    public void setPairingAnnotation(PairingAnnotation value) {
        this.pairingAnnotation = value;
    }

    /**
     * Gets the value of the timeAwayFromBase property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTimeAwayFromBase() {
        return timeAwayFromBase;
    }

    /**
     * Sets the value of the timeAwayFromBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTimeAwayFromBase(Duration value) {
        this.timeAwayFromBase = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setCredit(Duration value) {
        this.credit = value;
    }

    /**
     * Gets the value of the creditAnnotation property.
     * 
     * @return
     *     possible object is
     *     {@link CreditAnnotation }
     *     
     */
    public CreditAnnotation getCreditAnnotation() {
        return creditAnnotation;
    }

    /**
     * Sets the value of the creditAnnotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditAnnotation }
     *     
     */
    public void setCreditAnnotation(CreditAnnotation value) {
        this.creditAnnotation = value;
    }

    /**
     * Gets the value of the perDiem property.
     * 
     */
    public float getPerDiem() {
        return perDiem;
    }

    /**
     * Sets the value of the perDiem property.
     * 
     */
    public void setPerDiem(float value) {
        this.perDiem = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

}
